indexing-settings:
  sites:
    - url : http://www.playback.ru/
      name: Playback
    - url: https://www.svetlovka.ru/
      name: Svetlovka

server:
  port: 8080
#  servlet:
#    context-path: /final_project

spring:
  datasource:
    username: root
    password: 16s11w86d
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    org.hibernate: ERROR