version: "3.8"

services:
  mysqldb:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
    image: mysql:8
    restart: unless-stopped
    networks:
      - engine-network
    environment:
      - MYSQL_ROOT_PASSWORD=16s11w86d
      - MYSQL_DATABASE=search_engine
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy

    build:
      context: .
    networks:
      - engine-network
    ports:
      - 8080:8080
    environment:
      - spring_mvc_pathmatch_matching-strategy=ANT_PATH_MATCHER
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=16s11w86d
      - spring_jpa_hibernate_ddl-auto=update
      - INDEXING_SETTINGS_SITES_0_URL=http://www.playback.ru/
      - INDEXING_SETTINGS_SITES_0_NAME=Playback
      - INDEXING_SETTINGS_SITES_1_URL=https://www.svetlovka.ru/
      - INDEXING_SETTINGS_SITES_1_NAME=Svetlovka

    # Второй способ для чтения переменных из application.yaml путем создания volumes
    #    volumes:
    #      - ./application.yaml:/application.yaml
    stdin_open: true
    tty: true

volumes:
  db:

networks:
  engine-network:
    driver: bridge